# Generated by Django 6.0 on 2025-12-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('microsoft', 'Microsoft'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('lg', 'LG'), ('dell', 'Dell'), ('hp', 'HP'), ('apple', 'Apple'), ('lenovo', 'Lenovo'), ('asus', 'Asus'), ('apple', 'Apple'), ('htc', 'HTC'), ('nokia', 'Nokia'), ('blackberry', 'BlackBerry'), ('micromax', 'Micromax'), ('karbonn', 'Karbonn'), ('allbrand', 'All Brand')], max_length=100),
        ),
    ]
