# Generated by Django 6.0 on 2025-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
